[package]
name = "fpga"
version = "0.1.0"
edition = "2021"
rust-version = "1.62"

[lib]
name = "fpga"

[dependencies]
fpga-sys = { path = "sys", optional = true }
thiserror = "1"

[features]
default = ["f1"]
f1 = ["fpga-sys"]
